'use strict';
const $ = s => document.querySelector(s);
const defaults = {name:'未来的你',note:'你的表达、气质，以及那些还未充分展现的可能，都值得被认真看见、好好打磨。',code:'HF · INVITATION',date:'2026-10-23',contact:'和风传媒对接人'};
function readConfig(){try{const raw=new URLSearchParams(location.hash.slice(1)).get('invite');if(!raw)return defaults;const decoded=JSON.parse(new TextDecoder().decode(Uint8Array.from(atob(raw),c=>c.charCodeAt(0))));const conf={...defaults};for(const k of Object.keys(conf))if(typeof decoded[k]==='string')conf[k]=decoded[k].trim().slice(0,k==='note'?240:60)||defaults[k];if(!/^\d{4}-\d{2}-\d{2}$/.test(conf.date)||!Number.isFinite(Date.parse(conf.date)))conf.date=defaults.date;return conf;}catch{return defaults;}}
const config=readConfig();document.querySelectorAll('[data-recipient]').forEach(el=>el.textContent=config.name);document.querySelectorAll('[data-code]').forEach(el=>el.textContent=config.code);$('#personal-note').textContent=config.note;
const [year,month,day]=config.date.split('-');$('#launch-date').replaceChildren(document.createTextNode(`${month}.${day} `));const em=document.createElement('em');em.textContent=`/ ${year}`;$('#launch-date').append(em);
if(config.name!==defaults.name)$('#name').value=config.name.slice(0,24);
const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
$('#open-invitation').addEventListener('click',()=>{$('#open-invitation').classList.add('opened');$('#open-invitation').setAttribute('aria-expanded','true');$('#invitation-content').hidden=false;$('#tap-note').textContent='邀请已开启 · 轻触可再次阅读';setTimeout(()=>{$('#letter').scrollIntoView({behavior:reduced?'instant':'smooth'});resizeSignature();},reduced?0:620);});

// Store signature strokes in normalized coordinates, preserving them on rotation.
const canvas=$('#signature'),ctx=canvas.getContext('2d');let strokes=[],activeStroke=null,activePointer=null;
function redrawSignature(){const r=canvas.getBoundingClientRect();if(!r.width)return;const dpr=Math.min(devicePixelRatio||1,3);canvas.width=Math.round(r.width*dpr);canvas.height=Math.round(r.height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);ctx.strokeStyle='#183c32';ctx.fillStyle='#183c32';ctx.lineWidth=2.4;ctx.lineCap='round';ctx.lineJoin='round';for(const points of strokes){ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(p.x*r.width,p.y*r.height):ctx.moveTo(p.x*r.width,p.y*r.height));ctx.stroke();}if($('#typed-signature').checked){ctx.font='32px "Songti SC", SimSun, serif';ctx.textAlign='center';ctx.fillText($('#name').value.trim()||'请先填写姓名',r.width/2,r.height*.61);}$('#signature-hint').style.display=strokes.length||$('#typed-signature').checked?'none':'grid';}
function resizeSignature(){redrawSignature();}new ResizeObserver(resizeSignature).observe(canvas);
function point(e){const r=canvas.getBoundingClientRect();return{x:Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),y:Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))};}
canvas.addEventListener('pointerdown',e=>{if($('#typed-signature').checked||activePointer!==null)return;e.preventDefault();activePointer=e.pointerId;canvas.setPointerCapture(e.pointerId);activeStroke=[point(e)];strokes.push(activeStroke);redrawSignature();});canvas.addEventListener('pointermove',e=>{if(e.pointerId!==activePointer||!activeStroke)return;e.preventDefault();activeStroke.push(point(e));redrawSignature();});function stopStroke(e){if(e.pointerId!==activePointer)return;activeStroke=null;activePointer=null;}canvas.addEventListener('pointerup',stopStroke);canvas.addEventListener('pointercancel',stopStroke);canvas.addEventListener('lostpointercapture',stopStroke);
$('#clear-signature').addEventListener('click',()=>{strokes=[];activeStroke=null;activePointer=null;redrawSignature();});$('#typed-signature').addEventListener('change',redrawSignature);$('#name').addEventListener('input',()=>{if($('#typed-signature').checked)redrawSignature();});

function drawWrapped(c,text,x,y,maxWidth,lineHeight){let line='';for(const char of text){if(char==='\n'){c.fillText(line,x,y);line='';y+=lineHeight;continue;}if(c.measureText(line+char).width>maxWidth&&line){c.fillText(line,x,y);line=char;y+=lineHeight;}else line+=char;}if(line)c.fillText(line,x,y);return y+lineHeight;}
let receiptBlob=null;
async function makeReceipt(data){const out=document.createElement('canvas');out.width=1080;out.height=1560;const c=out.getContext('2d');c.fillStyle='#f6f3eb';c.fillRect(0,0,1080,1560);c.fillStyle='#173d32';c.fillRect(0,0,1080,215);c.fillStyle='#dfc18c';c.font='22px sans-serif';c.fillText('HEFENG MEDIA  /  INVITATION',74,65);c.fillStyle='#f6f3eb';c.font='48px "Songti SC", SimSun, serif';c.fillText('和风传媒 · 启程回执',74,150);c.fillStyle='#988157';c.font='23px sans-serif';c.fillText(config.code,74,270);c.fillStyle='#183c32';c.font='42px "Songti SC", SimSun, serif';c.fillText('我愿意，认真走这一程。',74,360);c.font='29px sans-serif';let y=drawWrapped(c,`${data.name}，确认收到和风传媒的合作邀请，愿意保持沟通，并按双方确认的安排完成开播准备。`,74,435,930,49);c.fillStyle='#77796d';c.font='22px sans-serif';c.fillText('倾向的开播方式',74,y+36);c.fillStyle='#183c32';c.font='32px sans-serif';c.fillText(data.mode,74,y+83);c.fillStyle='#77796d';c.font='22px sans-serif';c.fillText('想通过直播做到的一件事',74,y+148);c.fillStyle='#183c32';c.font='27px sans-serif';y=drawWrapped(c,data.goal||'先迈出这一步，再一起把方向聊清楚。',74,y+196,930,42);c.strokeStyle='#d9dbce';c.lineWidth=1;c.beginPath();c.moveTo(74,1085);c.lineTo(1006,1085);c.stroke();c.fillStyle='#77796d';c.font='22px sans-serif';c.fillText('我的签名',74,1100);if(data.typed){c.font='54px "Songti SC", SimSun, serif';c.fillStyle='#183c32';c.fillText(data.name,74,1180);}else{const rect=canvas.getBoundingClientRect();c.drawImage(canvas,74,1105,600,Math.min(155,600*rect.height/rect.width));}c.font='22px sans-serif';c.fillStyle='#77796d';c.fillText(data.signedDate,750,1180);c.fillStyle='#183c32';c.font='23px sans-serif';drawWrapped(c,'如时间或计划发生变化，我会提前与对接人说明。',74,1300,930,36);c.font='20px sans-serif';c.fillStyle='#77796d';drawWrapped(c,`预计合作启动：${year}年${month}月${day}日，具体安排另行确认。\n此回执表达合作意向，具体合作条件以双方正式确认为准。`,74,1380,930,33);c.fillStyle='#b18b52';c.font='21px sans-serif';c.fillText('和风与你，一起上场。',74,1510);const url=out.toDataURL('image/png');receiptBlob=await new Promise(resolve=>out.toBlob(resolve,'image/png'));$('#receipt-image').src=url;$('#download-receipt').href=url;$('#download-receipt').download=`和风传媒启程回执-${data.name.replace(/[<>:"/\\|?*]/g,'')}.png`;
}
$('#reply-form').addEventListener('submit',async e=>{e.preventDefault();const name=$('#name').value.trim(),mode=$('input[name=mode]:checked')?.value,typed=$('#typed-signature').checked;const errors=[];if(!name)errors.push('请填写你的名字或昵称');if(!mode)errors.push('请选择开播方式');const usable=strokes.some(s=>s.length>4&&s.some(p=>Math.hypot(p.x-s[0].x,p.y-s[0].y)>.025));if(!typed&&!usable)errors.push('请留下签名，或选择使用姓名落款');if(!$('#consent').checked)errors.push('请确认沟通与开播准备的约定');$('#form-error').textContent=errors.join('；');if(errors.length){if(!name)$('#name').focus();return;}const submit=$('#reply-form button[type=submit]');submit.disabled=true;try{await document.fonts.ready;await makeReceipt({name,mode,typed,goal:$('#goal').value.trim(),signedDate:new Date().toLocaleDateString('zh-CN',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'})});$('#share-status').textContent='';$('#receipt-dialog').showModal();}catch{$('#form-error').textContent='回执生成遇到问题，请重试。';}finally{submit.disabled=false;}});
$('#close-dialog').addEventListener('click',()=>$('#receipt-dialog').close());$('#receipt-dialog').addEventListener('click',e=>{if(e.target===$('#receipt-dialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}});
$('#share-receipt').addEventListener('click',async()=>{if(!receiptBlob)return;const f=new File([receiptBlob],'和风传媒启程回执.png',{type:'image/png'});if(navigator.canShare?.({files:[f]})){try{await navigator.share({files:[f],title:'我的和风启程回执'});}catch(e){if(e.name!=='AbortError')$('#share-status').textContent='请长按上方图片保存，再发给对接人。';}}else $('#share-status').textContent='当前浏览器不支持直接分享图片。请长按上方回执保存，再发送给和风对接人。';});
